version: "3"
services:
  app:
    container_name: nodeTube
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./app
      target: /usr/src/app
    tty: true
